crafting.addShapeless(item('gtuq:crude_knapped_stone'), [item('notreepunching:rock/stone'),item('notreepunching:rock/stone')])
mods.tconstruct.drying.recipeBuilder()
    .input(item('gtuq:rock_soaked_rawhide_crude_shovel'))
    .output(item('gtuq:rock_dried_rawhide_crude_shovel'))
    .time(1200)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item('gtuq:soaked_rawhide'))
    .output(item('gtuq:dried_rawhide'))
    .time(1500)
    .register()