crafting.addShapeless(item('gtuq:crude_knapped_stone'), [item('notreepunching:rock/stone'),item('notreepunching:rock/stone')])
crafting.addShapeless(item("gtuq:soaked_antler_billet"), [item("notreepunching:knife/flint").transformDamage(2).whenAnyDamage(),item("gtuq:soaked_antler")])
crafting.addShapeless(item('minecraft:dye', 15), [item('gtuq:antler_piece')])
crafting.addShapeless(item('gtuq:crude_knapped_flint'), [item('minecraft:flint'),item('minecraft:flint')])

ore_dict.add('knife', item('gtuq:crude_flint_soaked_rawhide_knife'))
ore_dict.add('knife', item('gtuq:crude_flint_dried_rawhide_knife'))
ore_dict.add('knife', item('gtuq:crude_flint_fiber_knife'))
crafting.addShapeless(item('gtuq:crude_soaked_antler_billet'), [item('gtuq:soaked_antler'),ore('knife').transformDamage(1).whenAnyDamage()])

mods.tconstruct.drying.recipeBuilder()
    .input(item('gtuq:rock_soaked_rawhide_crude_shovel'))
    .output(item('gtuq:rock_dried_rawhide_crude_shovel'))
    .time(1200)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item('gtuq:crude_flint_soaked_rawhide_knife'))
    .output(item('gtuq:crude_flint_dried_rawhide_knife'))
    .time(1200)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item('gtuq:soaked_rawhide'))
    .output(item('gtuq:dried_rawhide'))
    .time(1500)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item("gtuq:soaked_antler_billet"))
    .output(item("gtuq:antler_billet"))
    .time(1200)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item("gtuq:soaked_antler"))
    .output(item("betteranimalsplus:antler"))
    .time(1500)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item("gtuq:crude_soaked_antler_billet"))
    .output(item("gtuq:crude_antler_billet"))
    .time(1200)
    .register()
mods.tconstruct.drying.recipeBuilder()
    .input(item("gtuq:soaked_antler_piece"))
    .output(item("gtuq:antler_piece"))
    .time(600)
    .register()