in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 0.22f)
    .input(item('gtuq:rawhide'), 1.0f)
    .output(item('gtuq:soaked_rawhide'))
    .register()
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 0.12f)
    .input(item('betteranimalsplus:antler'), 1.0f)
    .output(item('gtuq:soaked_antler'))
    .register()
in_world_crafting.fluid_to_item.recipeBuilder()
    .fluidInput(fluid('water'), 0.10f)
    .input(item('gtuq:antler_billet'), 1.0f)
    .output(item('gtuq:soaked_antler_billet'))
    .register()